site_name: My Docs
site_url: https://argilla-io.github.io/observers
site_author: Argilla, Inc.
site_description: Distilabel is an AI Feedback (AIF) framework for building datasets with and for LLMs.

# Repository
repo_name: cfahlgren1/observers
repo_url: https://github.com/cfahlgren1/observers
edit_uri: edit/main/docs/