site_name: My Docs
site_url: https://argilla-io.github.io/distilabel
site_author: Argilla, Inc.
site_description: Distilabel is an AI Feedback (AIF) framework for building datasets with and for LLMs.

# Repository
repo_name: argilla-io/distilabel
repo_url: https://github.com/argilla-io/distilabel
edit_uri: edit/main/docs/